"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-01 04:15:44.613320
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actors",
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("external_ref", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("actor_type IN ('human', 'system')", name=op.f("ck_actors_actor_type")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actors")),
        sa.UniqueConstraint("external_ref", name=op.f("uq_actors_external_ref")),
        sa.UniqueConstraint("id", "actor_type", name="uq_actors_id_actor_type"),
    )
    op.create_table(
        "ai_employees",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("stage_key", sa.String(length=64), nullable=False),
        sa.Column("implementation_key", sa.String(length=64), nullable=True),
        sa.Column("llm_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allowed_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_format", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_format", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prompt_key", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'inactive')", name=op.f("ck_ai_employees_status")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_ai_employees_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_employees")),
        sa.UniqueConstraint("key", name=op.f("uq_ai_employees_key")),
    )
    op.create_table(
        "explorations",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("theme", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'archived')", name=op.f("ck_explorations_status")),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"],
            ["actors.id"],
            name=op.f("fk_explorations_created_by_actor_id_actors"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_explorations")),
    )
    op.create_table(
        "ideas",
        sa.Column("exploration_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("problem", sa.Text(), nullable=True),
        sa.Column("target_customer", sa.Text(), nullable=True),
        sa.Column("target_market", sa.Text(), nullable=True),
        sa.Column("revenue_model", sa.Text(), nullable=True),
        sa.Column("required_technology", sa.Text(), nullable=True),
        sa.Column("required_data", sa.Text(), nullable=True),
        sa.Column("competitor_info", sa.Text(), nullable=True),
        sa.Column("ip_info", sa.Text(), nullable=True),
        sa.Column("legal_regulatory_info", sa.Text(), nullable=True),
        sa.Column("initial_cost", sa.Text(), nullable=True),
        sa.Column("running_cost", sa.Text(), nullable=True),
        sa.Column("time_to_revenue", sa.Text(), nullable=True),
        sa.Column("scalability", sa.Text(), nullable=True),
        sa.Column("imitability", sa.Text(), nullable=True),
        sa.Column("ai_advantage", sa.Text(), nullable=True),
        sa.Column("origin_type", sa.String(length=16), nullable=False),
        sa.Column("origin_analysis_id", sa.Uuid(), nullable=True),
        sa.Column("adoption_status", sa.String(length=16), nullable=False),
        sa.Column("current_stage_key", sa.String(length=64), nullable=True),
        sa.Column("created_by_actor_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(origin_type = 'ai') = (origin_analysis_id IS NOT NULL)",
            name=op.f("ck_ideas_origin_analysis"),
        ),
        sa.CheckConstraint(
            "adoption_status IN ('candidate', 'adopted', 'rejected')",
            name=op.f("ck_ideas_adoption_status"),
        ),
        sa.CheckConstraint("origin_type IN ('human', 'ai')", name=op.f("ck_ideas_origin_type")),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"], ["actors.id"], name=op.f("fk_ideas_created_by_actor_id_actors")
        ),
        sa.ForeignKeyConstraint(
            ["exploration_id"],
            ["explorations.id"],
            name=op.f("fk_ideas_exploration_id_explorations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ideas")),
    )
    op.create_index(op.f("ix_ideas_exploration_id"), "ideas", ["exploration_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("exploration_id", sa.Uuid(), nullable=False),
        sa.Column("idea_id", sa.Uuid(), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=True),
        sa.Column("quote", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column("retracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retraction_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_type IN ('human_input', 'document', 'web', 'api', 'patent_db', 'other')",
            name=op.f("ck_evidence_source_type"),
        ),
        sa.CheckConstraint(
            "(retracted_at IS NULL) = (retraction_reason IS NULL)",
            name=op.f("ck_evidence_retraction_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_actor_id"],
            ["actors.id"],
            name=op.f("fk_evidence_created_by_actor_id_actors"),
        ),
        sa.ForeignKeyConstraint(
            ["exploration_id"],
            ["explorations.id"],
            name=op.f("fk_evidence_exploration_id_explorations"),
        ),
        sa.ForeignKeyConstraint(["idea_id"], ["ideas.id"], name=op.f("fk_evidence_idea_id_ideas")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_index(
        op.f("ix_evidence_exploration_id"), "evidence", ["exploration_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_idea_id"), "evidence", ["idea_id"], unique=False)
    op.create_table(
        "human_decisions",
        sa.Column("idea_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by_actor_type", sa.String(length=16), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("based_on_review_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decided_by_actor_type = 'human'", name=op.f("ck_human_decisions_decided_by_human")
        ),
        sa.CheckConstraint(
            "decision IN ('go', 'no_go', 'hold', 'pivot')", name=op.f("ck_human_decisions_decision")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_actor_id", "decided_by_actor_type"],
            ["actors.id", "actors.actor_type"],
            name="fk_human_decisions_decided_by_human",
        ),
        sa.ForeignKeyConstraint(
            ["idea_id"], ["ideas.id"], name=op.f("fk_human_decisions_idea_id_ideas")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_decisions")),
    )
    op.create_index(
        op.f("ix_human_decisions_idea_id"), "human_decisions", ["idea_id"], unique=False
    )
    op.create_table(
        "stage_runs",
        sa.Column("exploration_id", sa.Uuid(), nullable=False),
        sa.Column("idea_id", sa.Uuid(), nullable=True),
        sa.Column("stage_key", sa.String(length=64), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("rerun_of_id", sa.Uuid(), nullable=True),
        sa.Column("sent_back_from_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("research_question", sa.Text(), nullable=True),
        sa.Column("triggered_by_actor_id", sa.Uuid(), nullable=False),
        sa.Column("triggered_by_actor_type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(stage_key = 'idea_generation') = (idea_id IS NULL)",
            name=op.f("ck_stage_runs_scope_matches_stage"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')", name=op.f("ck_stage_runs_status")
        ),
        sa.CheckConstraint(
            "trigger IN ('initial', 'rerun', 'send_back')", name=op.f("ck_stage_runs_trigger")
        ),
        sa.CheckConstraint(
            "triggered_by_actor_type = 'human'", name=op.f("ck_stage_runs_triggered_by_human")
        ),
        sa.CheckConstraint("attempt_no >= 1", name=op.f("ck_stage_runs_attempt_positive")),
        sa.ForeignKeyConstraint(
            ["exploration_id"],
            ["explorations.id"],
            name=op.f("fk_stage_runs_exploration_id_explorations"),
        ),
        sa.ForeignKeyConstraint(
            ["idea_id"], ["ideas.id"], name=op.f("fk_stage_runs_idea_id_ideas")
        ),
        sa.ForeignKeyConstraint(
            ["rerun_of_id"], ["stage_runs.id"], name=op.f("fk_stage_runs_rerun_of_id_stage_runs")
        ),
        sa.ForeignKeyConstraint(
            ["sent_back_from_id"],
            ["stage_runs.id"],
            name=op.f("fk_stage_runs_sent_back_from_id_stage_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_actor_id", "triggered_by_actor_type"],
            ["actors.id", "actors.actor_type"],
            name="fk_stage_runs_triggered_by_human",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_runs")),
    )
    op.create_index(
        op.f("ix_stage_runs_exploration_id"), "stage_runs", ["exploration_id"], unique=False
    )
    op.create_index(op.f("ix_stage_runs_idea_id"), "stage_runs", ["idea_id"], unique=False)
    op.create_index(
        "uq_stage_runs_exploration_attempt",
        "stage_runs",
        ["exploration_id", "stage_key", "attempt_no"],
        unique=True,
        postgresql_where=sa.text("idea_id IS NULL"),
    )
    op.create_index(
        "uq_stage_runs_exploration_current",
        "stage_runs",
        ["exploration_id", "stage_key"],
        unique=True,
        postgresql_where=sa.text("idea_id IS NULL AND superseded_at IS NULL"),
    )
    op.create_index(
        "uq_stage_runs_idea_attempt",
        "stage_runs",
        ["idea_id", "stage_key", "attempt_no"],
        unique=True,
        postgresql_where=sa.text("idea_id IS NOT NULL"),
    )
    op.create_index(
        "uq_stage_runs_idea_current",
        "stage_runs",
        ["idea_id", "stage_key"],
        unique=True,
        postgresql_where=sa.text("idea_id IS NOT NULL AND superseded_at IS NULL"),
    )
    op.create_table(
        "executions",
        sa.Column("stage_run_id", sa.Uuid(), nullable=False),
        sa.Column("ai_employee_id", sa.Uuid(), nullable=False),
        sa.Column("idea_id", sa.Uuid(), nullable=True),
        sa.Column("ai_employee_version", sa.Integer(), nullable=False),
        sa.Column("ai_employee_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("implementation_key", sa.String(length=64), nullable=False),
        sa.Column("prompt_key", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=16), nullable=True),
        sa.Column("prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("llm_provider", sa.String(length=64), nullable=True),
        sa.Column("llm_model", sa.String(length=128), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_type", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "error_type IS NULL OR error_type IN ('validation_error', 'llm_error', 'tool_error', 'timeout', 'storage_error', 'unexpected')",
            name=op.f("ck_executions_error_type"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')", name=op.f("ck_executions_status")
        ),
        sa.ForeignKeyConstraint(
            ["ai_employee_id"],
            ["ai_employees.id"],
            name=op.f("fk_executions_ai_employee_id_ai_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["idea_id"], ["ideas.id"], name=op.f("fk_executions_idea_id_ideas")
        ),
        sa.ForeignKeyConstraint(
            ["stage_run_id"], ["stage_runs.id"], name=op.f("fk_executions_stage_run_id_stage_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
    )
    op.create_index(
        op.f("ix_executions_ai_employee_id"), "executions", ["ai_employee_id"], unique=False
    )
    op.create_index(op.f("ix_executions_idea_id"), "executions", ["idea_id"], unique=False)
    op.create_index(
        op.f("ix_executions_stage_run_id"), "executions", ["stage_run_id"], unique=False
    )
    op.create_table(
        "analyses",
        sa.Column("exploration_id", sa.Uuid(), nullable=False),
        sa.Column("idea_id", sa.Uuid(), nullable=True),
        sa.Column("stage_run_id", sa.Uuid(), nullable=False),
        sa.Column("execution_id", sa.Uuid(), nullable=False),
        sa.Column("stage_key", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "review_status IN ('pending_review', 'approved', 'rejected', 'changes_requested', 'needs_more_evidence')",
            name=op.f("ck_analyses_review_status"),
        ),
        sa.CheckConstraint("version_no >= 1", name=op.f("ck_analyses_version_positive")),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["executions.id"], name=op.f("fk_analyses_execution_id_executions")
        ),
        sa.ForeignKeyConstraint(
            ["exploration_id"],
            ["explorations.id"],
            name=op.f("fk_analyses_exploration_id_explorations"),
        ),
        sa.ForeignKeyConstraint(["idea_id"], ["ideas.id"], name=op.f("fk_analyses_idea_id_ideas")),
        sa.ForeignKeyConstraint(
            ["stage_run_id"], ["stage_runs.id"], name=op.f("fk_analyses_stage_run_id_stage_runs")
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"], ["analyses.id"], name=op.f("fk_analyses_supersedes_id_analyses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyses")),
    )
    op.create_index(op.f("ix_analyses_execution_id"), "analyses", ["execution_id"], unique=False)
    op.create_index(
        op.f("ix_analyses_exploration_id"), "analyses", ["exploration_id"], unique=False
    )
    op.create_index(op.f("ix_analyses_idea_id"), "analyses", ["idea_id"], unique=False)
    op.create_index(op.f("ix_analyses_stage_run_id"), "analyses", ["stage_run_id"], unique=False)
    # ideas <-> analyses は循環参照のため、両テーブル作成後に FK を追加する
    op.create_foreign_key(
        op.f("fk_ideas_origin_analysis_id_analyses"),
        "ideas",
        "analyses",
        ["origin_analysis_id"],
        ["id"],
    )
    op.create_table(
        "audit_events",
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("execution_id", sa.Uuid(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["actors.id"], name=op.f("fk_audit_events_actor_id_actors")
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
            name=op.f("fk_audit_events_execution_id_executions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_entity", "audit_events", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "analysis_evidence_links",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("claim_ref", sa.String(length=64), nullable=False),
        sa.Column("relation", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "relation IN ('supports', 'contradicts', 'context')",
            name=op.f("ck_analysis_evidence_links_relation"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
            name=op.f("fk_analysis_evidence_links_analysis_id_analyses"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_analysis_evidence_links_evidence_id_evidence"),
        ),
        sa.PrimaryKeyConstraint(
            "analysis_id", "evidence_id", "claim_ref", name=op.f("pk_analysis_evidence_links")
        ),
    )
    op.create_index(
        op.f("ix_analysis_evidence_links_evidence_id"),
        "analysis_evidence_links",
        ["evidence_id"],
        unique=False,
    )
    op.create_table(
        "human_reviews",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("exploration_id", sa.Uuid(), nullable=False),
        sa.Column("idea_id", sa.Uuid(), nullable=True),
        sa.Column("reviewer_actor_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_actor_type", sa.String(length=16), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("corrections", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('approve', 'reject', 'request_changes', 'needs_more_evidence')",
            name=op.f("ck_human_reviews_decision"),
        ),
        sa.CheckConstraint(
            "reviewer_actor_type = 'human'", name=op.f("ck_human_reviews_reviewer_is_human")
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"], ["analyses.id"], name=op.f("fk_human_reviews_analysis_id_analyses")
        ),
        sa.ForeignKeyConstraint(
            ["exploration_id"],
            ["explorations.id"],
            name=op.f("fk_human_reviews_exploration_id_explorations"),
        ),
        sa.ForeignKeyConstraint(
            ["idea_id"], ["ideas.id"], name=op.f("fk_human_reviews_idea_id_ideas")
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_actor_id", "reviewer_actor_type"],
            ["actors.id", "actors.actor_type"],
            name="fk_human_reviews_reviewer_human",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_reviews")),
    )
    op.create_index(
        op.f("ix_human_reviews_analysis_id"), "human_reviews", ["analysis_id"], unique=False
    )
    op.create_index(op.f("ix_human_reviews_idea_id"), "human_reviews", ["idea_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_ideas_origin_analysis_id_analyses"), "ideas", type_="foreignkey")
    op.drop_index(op.f("ix_human_reviews_idea_id"), table_name="human_reviews")
    op.drop_index(op.f("ix_human_reviews_analysis_id"), table_name="human_reviews")
    op.drop_table("human_reviews")
    op.drop_index(
        op.f("ix_analysis_evidence_links_evidence_id"), table_name="analysis_evidence_links"
    )
    op.drop_table("analysis_evidence_links")
    op.drop_index("ix_audit_events_entity", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_analyses_stage_run_id"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_idea_id"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_exploration_id"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_execution_id"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_index(op.f("ix_executions_stage_run_id"), table_name="executions")
    op.drop_index(op.f("ix_executions_idea_id"), table_name="executions")
    op.drop_index(op.f("ix_executions_ai_employee_id"), table_name="executions")
    op.drop_table("executions")
    op.drop_index(
        "uq_stage_runs_idea_current",
        table_name="stage_runs",
        postgresql_where=sa.text("idea_id IS NOT NULL AND superseded_at IS NULL"),
    )
    op.drop_index(
        "uq_stage_runs_idea_attempt",
        table_name="stage_runs",
        postgresql_where=sa.text("idea_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_stage_runs_exploration_current",
        table_name="stage_runs",
        postgresql_where=sa.text("idea_id IS NULL AND superseded_at IS NULL"),
    )
    op.drop_index(
        "uq_stage_runs_exploration_attempt",
        table_name="stage_runs",
        postgresql_where=sa.text("idea_id IS NULL"),
    )
    op.drop_index(op.f("ix_stage_runs_idea_id"), table_name="stage_runs")
    op.drop_index(op.f("ix_stage_runs_exploration_id"), table_name="stage_runs")
    op.drop_table("stage_runs")
    op.drop_index(op.f("ix_human_decisions_idea_id"), table_name="human_decisions")
    op.drop_table("human_decisions")
    op.drop_index(op.f("ix_evidence_idea_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_exploration_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_ideas_exploration_id"), table_name="ideas")
    op.drop_table("ideas")
    op.drop_table("explorations")
    op.drop_table("ai_employees")
    op.drop_table("actors")
    # ### end Alembic commands ###
